
NumPy Fundamentals for Deep Learning
======================================================

A comprehensive exploration of NumPy operations essential for scientific computing
and deep learning applications in hydrology, climate science, and earth observations.

Author: Kumar Puran Tripathy
Purpose: Pedagogical notebook for Chapter 2 - Mathematical Structures and Computational Primitives


##### ============================================================================
##### SECTION 1: IMPORTING AND UNDERSTANDING THE NUMPY PARADIGM
##### ============================================================================

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
print("NumPy version:", np.__version__)
print("\nNumPy represents the computational foundation upon which all scientific")
print("Python computing is built. Understanding its architecture is non-negotiable")
print("for deep learning practitioners.\n")

NumPy version: 1.26.4

NumPy represents the computational foundation upon which all scientific
Python computing is built. Understanding its architecture is non-negotiable
for deep learning practitioners.



##### ============================================================================
##### SECTION 2: ARRAY CREATION - FOUNDATIONAL CONSTRUCTORS
##### ============================================================================

In [2]:
temperature_anomalies = np.array([1.2, 0.8, 1.5, 2.1, 1.9])
print(f"1D Temperature anomalies: {temperature_anomalies}")
print(f"   Shape: {temperature_anomalies.shape}")
print(f"   Dtype: {temperature_anomalies.dtype}")
print(f"   Ndim: {temperature_anomalies.ndim}")

1D Temperature anomalies: [1.2 0.8 1.5 2.1 1.9]
   Shape: (5,)
   Dtype: float64
   Ndim: 1


In [3]:
# 2D array construction
sst_data = np.array([[15.2, 16.1, 15.8],
                     [14.9, 15.5, 16.0]])
print(f"\n2D SST data:\n{sst_data}")
print(f"   Shape: {sst_data.shape} (rows, columns)")
print(f"   Ndim: {sst_data.ndim}")


2D SST data:
[[15.2 16.1 15.8]
 [14.9 15.5 16. ]]
   Shape: (2, 3) (rows, columns)
   Ndim: 2


In [4]:
# 3D array construction - common in spatio-temporal data
# Shape: (time, latitude, longitude)
monthly_precip = np.array([
    [[12, 15, 10], [8, 9, 11]],   # January
    [[10, 12, 9], [7, 8, 10]],    # February
    [[14, 16, 13], [9, 11, 12]]   # March
])
print(f"\n3D Monthly precipitation (time, lat, lon):\n{monthly_precip}")
print(f"   Shape: {monthly_precip.shape}")
print(f"   Interpretation: {monthly_precip.shape[0]} months, {monthly_precip.shape[1]} latitudes, {monthly_precip.shape[2]} longitudes")



3D Monthly precipitation (time, lat, lon):
[[[12 15 10]
  [ 8  9 11]]

 [[10 12  9]
  [ 7  8 10]]

 [[14 16 13]
  [ 9 11 12]]]
   Shape: (3, 2, 3)
   Interpretation: 3 months, 2 latitudes, 3 longitudes
